emit:
  - "@typespec/openapi3"

options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/openapi/{version}"
    output-file: "openapi.yaml"

linter:
  extends:
    - "@moovfinancial/tsp-lib/recommended"
