workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    latest:
        inputs:
            - location: ./openapi/latest/openapi.yaml
            - location: ./openapi/v2024.00.00/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/moov/moov/latest
targets:
    go-latest:
        target: go
        source: latest
        output: ./output/go-latest
